// <auto-generated />
namespace Spice_DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MenuIdaddedintableOrderSummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuIdaddedintableOrderSummary));
        
        string IMigrationMetadata.Id
        {
            get { return "202102280637006_MenuId added in table OrderSummary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
